services:
  glory-admin:
    build: './'
    # context: .
    container_name: "glory-admin"
    # restart: always
    # working_dir: "/target"
    entrypoint: /bin/bash
    command: -c "chmod +x glory-admin && ./glory-admin"
    ports:
      - 8100:8100
    environment:
      GLORY_SITE_ADDR: "0.0.0.0:8100"
    volumes:
      - "./target:/target"
      # - "./public:/site/public"
      # - "./Cargo.toml:/site/Cargo.toml"
      - "./target/server/release/glory-admin:/glory-admin"